services:
  okkam.cars.webapi:
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - 6085:8080
      - 6081:8081
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ../apps/logs:/data
  minio:
    image: minio/minio:latest
    ports:
      - "9000"
      - "9001"
    volumes:
      - minio:/data
    environment:
      - "MINIO_ROOT_USER=minio"
      - "MINIO_ROOT_PASSWORD=password"
      - "MINIO_ACCESS_KEY=minio"
      - "MINIO_SECRET_KEY=password"
    entrypoint: >
      /bin/sh -c '
        isAlive() { curl -sf http://127.0.0.1:9000/minio/health/live; }    
        minio $0 "$@" --quiet & echo $! > /tmp/minio.pid                   
        while ! isAlive; do sleep 0.1; done                                
        mc alias set minio http://127.0.0.1:9000 minio password       
        mc mb minio/cars || true                                    
        mc anonymous set public minio/cars                          
        kill -s INT $(cat /tmp/minio.pid) && rm /tmp/minio.pid             
        while isAlive; do sleep 0.1; done                                  
        exec minio $0 "$@"'                                                 
      
    command: server --console-address ":9001" /data 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 20
      
  
  postgres:
    image: postgres:14-alpine
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 20s
      retries: 20
    ports:
      - "5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cars_db 


volumes:
  minio: {}
  postgres: {}